steps:
  - name: gradle:5.6.2-jdk11
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk11
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/matches-product-api/papi", "--build-arg=JAR_FILE=build/libs/papi-1.0.0.jar", "."]
images: ["gcr.io/matches-product-api/papi"]